FROM python:3.10.14-slim-bullseye

EXPOSE 80
EXPOSE 443

RUN apt-get update && apt-get install -y

RUN pip install poetry==1.4.2

# Configuring poetry
RUN poetry config virtualenvs.create false

# Copying requirements of a project
COPY pyproject.toml poetry.lock /app/src/
WORKDIR /app/src

# Copying actual application
COPY . /app/src/
RUN poetry install

CMD ["/usr/local/bin/python", "llm_api/app/run_app.py"]