version: '3.8'

services:
  backend:
    build:
      context: ./llm_api
      dockerfile: Dockerfile
    image: llm_api
    container_name: llm_api_container
    ports:
      - "8000:8000"
    volumes:
      - ./llm_api:/app/llm_api
    environment:
      LLM_API_HOST: 0.0.0.0
    restart: always

  frontend:
    build:
      context: ./llm_react
      dockerfile: Dockerfile
    image: llm_react
    container_name: llm_react_container
    ports:
      - "3000:3000"
    volumes:
      - ./llm_react:/app
      - ./llm_react/node_modules:/app/node_modules
    restart: always
    tty: true
    stdin_open: true
    command: npm run dev
