version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  uvicorn:
    format: "%(levelprefix)s %(asctime)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
  file:
    class: logging.FileHandler
    formatter: default
    filename: app.log
loggers:
  uvicorn:
    handlers: ["console"]
    level: INFO
    propagate: False
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: ["console", "file"]
    level: INFO
    propagate: False
  app_logger:
    handlers: ["console", "file"]
    level: DEBUG
    propagate: False
root:
  level: INFO
  handlers: ["console", "file"]
